### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Yardanico** [Yardanico/ircord#1]
Bugs:
- [x] When using # to mention a user (regression) or a channel in Discord, the IRC message looks like that:
```
<Yardanico> So Discord's <#371759607934353448> was separate from IRC's #nim-offtopic for a long time
```
Same for Discord emotes like ``:nim1:``, ``:nim2:``.
- [ ] Possible crashes, need to track as many as possible in both dimscord and ircord itself so that the bot can work for longer periods of time without restarting.

- [x] Multiline messages aren't displayed well by the bot (they're simply trimmed)
- [x] IRC colors are not being stripped
- [x] Discord mentions are being displayed as if the author mentioned themselves
Features:
- [x] Proper edit diffing (possibly with colors for add (green) remove (red))
- [x] Ability to mention Discord users from IRC
- [x] Ability to ban Discord users from IRC (doesn't work after a switch to dimscord, need to fix) 
- [x] Proper handling of big messages (over 500 characters or over 2 newlines or contains ```)

**Comment by krisppurg** [comment]
Any more updates from this?

**Comment by Yardanico** [comment]
Seems like all from this has been done, and tracking all stuff in the same issue is bad anyway. Closing.
